### ISSUE TITLE
Unable to create user account in demo

### ISSUE THREAD

**Issue by sablair** [rahulbaisla/sentimentAnalysisLab#1]
After completing all the steps to run this sample, I get an authentication error when trying to create a new account:
<img width="754" alt="Screenshot 2021-02-24 at 1 35 45 PM" src="https://user-images.githubusercontent.com/3528901/108958540-15f99f80-76ae-11eb-90bb-387c4e78c560.png">

I used the inspector and saw this:
<img width="789" alt="Screenshot 2021-02-24 at 1 36 04 PM" src="https://user-images.githubusercontent.com/3528901/108958665-40e3f380-76ae-11eb-80ca-14fbde700385.png">

I would love some help identifying what happened and how can I fix it to run.

*Side note: I was not able to get the app running on a t2 instance, but that was resolved after changing to a t3 instance.*

**Comment by chaundhyan** [comment]
Same here.
Tried both on my local setup and also on Cloud9.

**Comment by rahulbaisla** [comment]
This issue was because of an old package aws-amplify package version and has been updated. Please try with the latest version of the package.json
