### ISSUE TITLE
Test application has problem

### ISSUE THREAD

**Issue by calich88** [rahulbaisla/sentimentAnalysisLab#2]
Dear Admin,
From beginning to Push the Backend to AWS Cloud is ok
however, "npm run start" had the error 
---
```
The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! devlabsummit@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the devlabsummit@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2021-02-24T09_29_44_189Z-debug.log
ec2-user:~/environment/sentimentAnalysisLab (master) $ `
```

**Comment by WernHui** [comment]
I am also facing the exact same issue.

**Comment by rahulbaisla** [comment]
The issue can be resolved by modifying the Cloud9 environment to use a t3.medium instance type. See updated instructions in README.md 

Ifyou may face issues related to no space left on device. Follow the instructions in below AWS Documentation to modify the storage volume.

[Resize an Amazon EBS volume used by an environment](https://docs.aws.amazon.com/cloud9/latest/user-guide/move-environment.html#move-environment-resize)
